version: '3.7'

services:
  ap:
    image: ${IMAGE_AP_REPOSITORY}:${IMAGE_AP_TAG}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
  db:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # ports:
    #   - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./config/mysql/conf.d:/etc/mysql/conf.d
      - mysql-data:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

volumes:
  mysql-data:
    driver: local
