version: '3.7'

services:
  web:
    image: nginx:1.17.5-alpine
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
    # nginx - Docker Hub
    # Running nginx in debug mode
    #   https://hub.docker.com/_/nginx
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - ap
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
  ap:
    image: ${IMAGE_AP_REPOSITORY}:${IMAGE_AP_TAG}
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
  db:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # ports:
    #   - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - ./config/mysql/conf.d:/etc/mysql/conf.d
      - ./log:/var/log/mysql:cached
      - mysql-data:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

volumes:
  mysql-data:
    driver: local
