version: 2.1
jobs:
  build:
    environment:
      IMAGE_AP_REPOSITORY: bbs
      IMAGE_AP_TAG: test
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: docker build -f ./src/Dockerfile --target test -t ${IMAGE_AP_REPOSITORY}:${IMAGE_AP_TAG} .
          working_directory: backend
      - run:
          name: Run lint
          command: docker run --rm ${IMAGE_AP_REPOSITORY}:${IMAGE_AP_TAG} lint
      - run:
          name: Run test
          command: docker run --rm ${IMAGE_AP_REPOSITORY}:${IMAGE_AP_TAG} test
