version: '3.7'

services:
  web:
    ports:
      - "80:80"
  ap:
    image: ${IMAGE_AP_REPOSITORY}:development
    build:
      dockerfile: ./.devcontainer/Dockerfile
      context: .
    volumes:
      - .:/workspace:cached
      # ログの永続化
      - ./log:/var/log/bbs:cached
      # ホストのホームディレクトリ
      - ~:/localhost_home:ro
      # Dokcerコンテナ内からDockerを使う Docker outside of Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # コンテナリビルド時に拡張機能の再インストールを避ける
      # - vscode-server:/root/.vscode-server:z
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  vscode-server:
