version: 1
disable_existing_loggers: False
formatters:
  simple_formatter:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(request_id)s - %(message)s"
filters:
  request_context_filter:
    (): app.logging.RequestContextFilter
handlers:
  console_handler:
    class: logging.StreamHandler
    level: WARNING
    filters:
      - request_context_filter
    formatter: simple_formatter
    stream: ext://sys.stdout
  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    filters:
      - request_context_filter
    formatter: simple_formatter
    filename: /var/log/bbs/debug.log
    # 1MB (1024 * 1024 * 1024) でロールオーバし、1ファイルだけバックアップする
    maxBytes: 1073741824
    backupCount: 1
    encoding: utf8
  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    filters:
      - request_context_filter
    formatter: simple_formatter
    filename: /var/log/bbs/info.log
    maxBytes: 1073741824
    backupCount: 1
    encoding: utf8
  # INFO は不要だけど WARNING は必要なときに使う
  warning_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    filters:
      - request_context_filter
    formatter: simple_formatter
    filename: /var/log/bbs/info.log
    maxBytes: 1073741824
    backupCount: 1
    encoding: utf8
  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    filters:
      - request_context_filter
    formatter: simple_formatter
    filename: /var/log/bbs/error.log
    maxBytes: 1073741824
    backupCount: 1
    encoding: utf8
loggers:
  app:
    level: DEBUG
    handlers:
      # 開発時には WARNING 以上のログをすぐに見られるようにしたいのでコンソール出力する
      - console_handler
      - debug_file_handler
      - info_file_handler
      - error_file_handler
    # rootロガー でも同じハンドラーを設定しているため propagate: False にしないと、同じログが2回出力される
    propagate: False
  sqlalchemy.engine:
    level: INFO
    handlers:
      - debug_file_handler
    # WARNING 以上のログは rootロガーでハンドリングするため propagate: True にする
    propagate: True
# rootロガーは WARNING 以上をハンドリングする
root:
  level: WARNING
  handlers:
    - console_handler
    - warning_file_handler
    - error_file_handler
