version: 1
disable_existing_loggers: False
formatters:
  simple_formatter:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(request_id)s - %(message)s"
filters:
  request_context_filter:
    (): app.logging.RequestContextFilter
handlers:
  debug_file_handler:
    class: logging.FileHandler
    level: DEBUG
    filters:
      - request_context_filter
    formatter: simple_formatter
    filename: logs/debug.log
    encoding: utf8
  info_file_handler:
    class: logging.FileHandler
    level: INFO
    filters:
      - request_context_filter
    formatter: simple_formatter
    filename: logs/info.log
    encoding: utf8
  error_file_handler:
    class: logging.FileHandler
    level: ERROR
    filters:
      - request_context_filter
    formatter: simple_formatter
    filename: logs/error.log
    encoding: utf8
loggers:
  app:
    level: DEBUG
    handlers:
      - debug_file_handler
      - info_file_handler
      - error_file_handler
    propagate: False
  sqlalchemy.engine:
    level: INFO
    handlers:
      - debug_file_handler
    propagate: False
root:
  level: INFO
  handlers:
    - info_file_handler
    - error_file_handler
