version: '3.7'

services:
  web:
    ports:
      - "80:80"
  ap:
    build:
      target: production
      context: .
      dockerfile: ./src/Dockerfile
    volumes:
      - ./log:/var/log/bbs:cached
